int a = 5;
int b = 8;
int c = 9;
int d = 3;
int e = 15;
int max = a;
if (b > max) max = b;
if (c > max) max = c;
if (d > max) max = d;
if (e > max) max = e;
Console.Write("max = ");
Console.WriteLine(max);